name: Coffeecount
options:
  bundleIdPrefix: com.shimondeitel.coffeecount
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Coffeecount:
    type: application
    platform: iOS
    sources:
      - path: Coffeecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coffeecount
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Coffeecount/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  CoffeecountTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CoffeecountTests
      - path: Coffeecount.storekit
    dependencies:
      - target: Coffeecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coffeecount.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  CoffeecountUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CoffeecountUITests
    dependencies:
      - target: Coffeecount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.coffeecount.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Coffeecount:
    build:
      targets:
        Coffeecount: all
        CoffeecountTests: [test]
        CoffeecountUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Coffeecount.storekit
    test:
      config: Debug
      storeKitConfiguration: Coffeecount.storekit
      targets:
        - CoffeecountTests
        - CoffeecountUITests
    archive:
      config: Release
